#
server:
  port: 7002
  #
spring:
  #设置采样率默认为 0.1 注意之前的版本是percentage 新版本中更换为 probability
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: api-chat-contacts
    sender:
      type: web
  #-------
  application:
    name: api-chat-contacts
#
##配置 Eureka注册中心与发现中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://mr:123456@localhost:8761/eureka

##开启熔断器机制
feign:
  circuitbreaker:
    enabled: true
